[package]
name = "api"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
mongodb = "0.4.0"
[[bin]]
name = "api"
path = "api.rs"
